In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("sales_report.csv")

df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [7]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [9]:
df.shape

(12575, 11)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [11]:
df.dtypes

Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
dtype: object

In [12]:
df.columns.tolist()

['Transaction ID',
 'Customer ID',
 'Category',
 'Item',
 'Price Per Unit',
 'Quantity',
 'Total Spent',
 'Payment Method',
 'Location',
 'Transaction Date',
 'Discount Applied']

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [15]:
df[numeric_cols].describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean         0.510164      0.504042      0.307784
std          0.298431      0.317543      0.233952
min          0.000000      0.000000      0.000000
25%          0.250000      0.222222      0.113580
50%          0.500000      0.555556      0.255556
75%          0.791667      0.777778      0.461728
max          1.000000      1.000000      1.000000

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Category_encoded'] = le.fit_transform(df['Category'])

In [18]:
df[['Category', 'Category_encoded']].head()

        Category  Category_encoded
0     Patisserie                 7
1  Milk Products                 6
2       Butchers                 1
3      Beverages                 0
4           Food                 4

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    df[col + '_encoded'] = le.fit_transform(df[col])

In [20]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Category_encoded,Transaction ID_encoded,Customer ID_encoded,Item_encoded,Payment Method_encoded,Location_encoded,Transaction Date_encoded,Discount Applied_encoded
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,0.375000,1.000000,0.444444,Digital Wallet,Online,2024-04-08,True,7,8150,8,7,2,1,828,1
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,0.666667,0.888889,0.632099,Digital Wallet,Online,2023-07-23,True,6,3767,21,62,2,1,568,1
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,0.458333,0.111111,0.093827,Credit Card,Online,2022-10-05,False,1,11597,1,17,1,1,277,0
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,0.625000,0.888889,0.598765,Credit Card,Online,2022-05-07,NaN,0,11796,5,48,1,1,126,2
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,0.208333,0.666667,0.203704,Digital Wallet,Online,2022-10-02,False,4,4999,4,172,2,1,274,0

In [22]:
skewness = df.skew(numeric_only=True)

print("Skewness of numerical features:")
print(skewness)

Skewness of numerical features:
Price Per Unit             -0.034977
Quantity                   -0.011948
Total Spent                 0.831295
Category_encoded           -0.003702
Transaction ID_encoded      0.000000
Customer ID_encoded        -0.003838
Item_encoded               -0.023254
Payment Method_encoded      0.024356
Location_encoded           -0.021157
Transaction Date_encoded   -0.011168
Discount Applied_encoded   -0.006127
dtype: float64

In [23]:
highly_skewed = skewness[abs(skewness) > 1]
print("Highly Skewed Features:")
print(highly_skewed)

Highly Skewed Features:
Series([], dtype: float64)

In [25]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Category_encoded,Transaction ID_encoded,Customer ID_encoded,Item_encoded,Payment Method_encoded,Location_encoded,Transaction Date_encoded,Discount Applied_encoded
0,8150,8,7,7,0.375000,1.000000,0.444444,2,1,828,1,7,8150,8,7,2,1,828,1
1,3767,21,6,62,0.666667,0.888889,0.632099,2,1,568,1,6,3767,21,62,2,1,568,1
2,11597,1,1,17,0.458333,0.111111,0.093827,1,1,277,0,1,11597,1,17,1,1,277,0
3,11796,5,0,48,0.625000,0.888889,0.598765,1,1,126,2,0,11796,5,48,1,1,126,2
4,4999,4,4,172,0.208333,0.666667,0.203704,2,1,274,0,4,4999,4,172,2,1,274,0